### ISSUE TITLE
Add logic for toggling categories

### ISSUE THREAD

**Issue by e0** [Dynastybball/DynastyBball#2]

**Comment by Dynastybball** [comment]
No - I just wanted to confirm that I needed to switch, which I just did and tested it out. And it looks to be worked perfectly. It looks great!

**Comment by e0** [comment]
Ok, good that you got it to work! The first step was just making it functional of course. There is minimum styling at this point and we can make things look a lot prettier etc.

I think the next step to make it closer to the original would be to hide the  last two columns and add color coding for the table cells. I think we can close this issue for now but please feel free to create some new issues for what you would like to change next.

**Comment by Dynastybball** [comment]
fantastic. I'll open up a few now!
